import { defineField, defineType } from 'sanity'

export const servicePageType = defineType({
  name: 'servicePage',
  title: 'Service Pages',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Service Name',
      type: 'string',
      description: 'The full name of this service. Shown as the card title on /services and as the H1 on the detail page.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'Used in the URL: /services/[slug]. Must be lowercase with hyphens.',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow',
      type: 'string',
      description: 'Small category label shown above the title on the detail page. Examples: Full Builds, Focused Pages, Search Foundations.',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      description: 'Shown on the /services card. Keep under 220 characters. This is the summary visible to visitors browsing services.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title',
      type: 'string',
      description: 'Shown in browser tabs and search results. Keep under 60 characters.',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'string',
      description: 'Shown in Google search results. Keep under 160 characters.',
      validation: (Rule) => Rule.required().max(160),
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline',
      type: 'string',
      description: 'Main H1 on the service detail page.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroSubheadline',
      title: 'Hero Subheadline',
      type: 'text',
      rows: 2,
      description: 'Intro copy shown below the H1.',
    }),
    defineField({
      name: 'whoThisIsFor',
      title: 'Who This Is For',
      type: 'text',
      rows: 3,
      description: 'Qualifies the visitor. Explain what kind of business or situation this service fits.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'problemsSolved',
      title: 'Problems Solved',
      type: 'array',
      description: 'Bullet list of pain points this service addresses.',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'includedItems',
      title: "What's Included",
      type: 'array',
      description: 'Bullet list of what the client receives.',
      of: [{ type: 'string' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'businessBenefits',
      title: 'Business Benefits',
      type: 'array',
      description: "Bullet list of why the included items matter to the client's business.",
      of: [{ type: 'string' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'notFor',
      title: 'Not For',
      type: 'text',
      rows: 2,
      description: 'Optional disqualification copy. Use this to prevent wrong-fit inquiries. Example for Ongoing Support: clarify this is only for sites you build, not WordPress/Wix/Squarespace maintenance.',
    }),
    defineField({
      name: 'body',
      title: 'Body Copy',
      type: 'array',
      description: 'Long-form editorial content. Write 400–800 words of prose that explains the service approach, methodology, and what makes this work. Paragraph text that Google can index.',
      of: [
        defineField({
          name: 'block',
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'Heading 2', value: 'h2' },
            { title: 'Heading 3', value: 'h3' },
            { title: 'Quote', value: 'blockquote' },
          ],
          marks: {
            decorators: [
              { title: 'Strong', value: 'strong' },
              { title: 'Emphasis', value: 'em' },
            ],
            annotations: [
              defineField({
                name: 'link',
                title: 'External Link',
                type: 'object',
                fields: [
                  defineField({ name: 'href', title: 'URL', type: 'url' }),
                  defineField({ name: 'blank', title: 'Open in new tab', type: 'boolean', initialValue: true }),
                ],
              }),
            ],
          },
        }),
      ],
    }),
    defineField({
      name: 'faqs',
      title: 'FAQs',
      type: 'array',
      description: 'Frequently asked questions about this service.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'question', title: 'Question', type: 'string', validation: (Rule) => Rule.required() }),
            defineField({ name: 'answer', title: 'Answer', type: 'text', rows: 3, validation: (Rule) => Rule.required() }),
          ],
          preview: { select: { title: 'question' } },
        },
      ],
    }),
    defineField({
      name: 'relatedServices',
      title: 'Related Services',
      type: 'array',
      description: 'Other service pages to link from the bottom of this page. Sanity will resolve these to title and slug.',
      of: [{ type: 'reference', to: [{ type: 'servicePage' }] }],
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sort Order',
      type: 'number',
      description: 'Controls display order on the /services hub. Lower numbers appear first.',
    }),
    defineField({
      name: 'featuredOnHub',
      title: 'Show on Services Hub',
      type: 'boolean',
      description: 'Uncheck to hide this service from the /services card grid without deleting the document.',
      initialValue: true,
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      description: 'Optional. Record when this page went live.',
    }),
  ],
})
